### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by alex-njuguna** [Joymutheu-dev/MISSING-PERSONS-DATABASE-2024-KENYA-FINANCE-BILL-PROTESTS-#1]
Suppose we had an updatable status field in the model with choices to mark individuals already found, comfirmed dead and still missing.

**Comment by Joymutheu-dev** [comment]
> Suppose we had an updatable status field in the model with choices to mark individuals already found, comfirmed dead and still missing.

Noted
